---
- name: Ansible SDK
  hosts: scrappers
  gather_facts: false

  pre_tasks:

    - name: Include Pre-Tasks
      include_tasks: pretasks.yml

  tasks:

    - name: Debug SDK Base Dir
      debug:
        var: base_dir

    - name: Debug SDK Common
      debug:
        var: common

    - name: Debug SDK Secrets
      debug:
        var: secrets

  roles:
    - role: postgreSQL_server
      sdk_action: create

    - role: geerlingguy.postgresql
      become: yes
